spring.application.name=estoque-api

spring.datasource.url=jdbc:postgresql://localhost:5432/estoque_api
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Endpoints expostos via HTTP (separados por vírgula)
management.endpoints.web.exposure.include=health,info

# Mostrar detalhes do health — útil em desenvolvimento
# Em produção: "when-authorized" ou "never"
#management.endpoint.health.show-details=always
management.info.env.enabled=true

# Informações do /actuator/info
info.app.name=Estoque API
info.app.description=API REST para gerenciamento de estoque
info.app.version=0.6.0